[tool.poetry]
name = "calcfw"
version = "0.4.0-alpha.7"
description = "Distributed calculation framework"
readme = "README.md"
authors = ["Jan Hermann <dev@janhermann.cz>"]
repository = "https://github.com/azag0/calcfw"
documentation = "https://janhermann.cz/calcfw"
license = "MPL-2.0"
packages = [
    { include = "caf2" },
]
classifiers = [
    "Development Status :: 3 - Alpha",
    "Environment :: Console",
    "Intended Audience :: Developers",
    "Intended Audience :: Science/Research",
    "Natural Language :: English",
    "Operating System :: POSIX",
    "Topic :: Scientific/Engineering",
    "Topic :: Utilities"
]

[tool.poetry.dependencies]
python = "^3.7"
typing_extensions = "^3.6"
mypy_extensions = "^0.4.1"
graphviz = { version = "^0.9.0", optional = true }
numpy = { version = "^1.15", optional = true }
textx = { version = "~1.5", optional = true }

[tool.poetry.extras]
graphviz = ["graphviz"]
sci = ["numpy", "textx"]

[tool.poetry.dev-dependencies]
pytest = "^3.8"
coverage = "^4.5"
mypy = "^0.630.0"
lxml = "^4.2"
sphinx = "^1.8"
toml = "^0.9.6"
