[tool.poetry]
name = "caf"
version = "0.4.0"
description = "Distributed calculation framework"
authors = ["Jan Hermann <dev@janhermann.cz>"]
license = "MPL-2.0"

[tool.poetry.dev-dependencies]
pytest = "^3.8"
coverage = "^4.5"
